global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'budget-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['budget-service:8080']

  - job_name: 'analytic-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['analytic-service:8080']
